### ISSUE TITLE
prefer using simple quote over double quote 

### ISSUE THREAD

**Issue by mincong-h** [jingwen-z/bigdata-ucsd#1]
Hi @jingwen-z,

I saw that you're using both simple quote `'` and double quote `"` inside your python scripts. Both of the are valid syntax. However, I would prefer using simple quote for all the string expression which gives an unicity of the script.

### Bad

```python
df.describe('rain_accumulation_9am').show()
df.count() - 1089
...
df.stat.corr("relative_humidity_9am", "relative_humidity_3pm")
```

### Good

```python
df.describe('rain_accumulation_9am').show()
df.count() - 1089
...
df.stat.corr('relative_humidity_9am', 'relative_humidity_3pm')
```

The only exception will be for documentation string: according to [PEP 257][257], double quote `"""` is preferred over `'''`.

[257]: https://www.python.org/dev/peps/pep-0257/

**Comment by jingwen-z** [comment]
Hi @mincong-h,

Thanks for your reviewing, the idea is really constructive. All double quotes are updated to simple quotes, except for documentation string.

**Comment by mincong-h** [comment]
It seems that you've changed your code without testing the result. See comments inside you commit 16a3ef8 to have more detail.

**Comment by jingwen-z** [comment]
I recoded in python notebook, replace `.py` by `.ipynb`. All scripts work well.

**Comment by mincong-h** [comment]
great 👍
